version: 2.1
jobs:
  build:
    docker:
      - image: alpine
        auth:
          username: docker_username
          password: docker_password
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World'
            echo 'This is the delivery pipeline'